steps:
# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args: ['-c', 'docker pull gcr.io/dtumlops-410818/training:latest || exit 0']      '--cache-from', 'gcr.io/dtumlops-410818/training:latest', 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'dockerfiles/trainer-cloud.dockerfile', '-t', 'gcr.io/dtumlops-410818/training:latest', '.']
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp -r -v gs://dtumlops_data_bucket/data/processed/ data/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-410818/training']
