steps:
# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args: ['-c', 'docker pull gcr.io/dtumlops-410818/predict:latest || exit 0']   '--cache-from', 'gcr.io/dtumlops-410818/predict:latest', 
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir models
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp -v gs://dtumlops_data_bucket/models/model.pt models/
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'dockerfiles/predict-cloud.dockerfile', '-t', 'gcr.io/dtumlops-410818/predict:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-410818/predict']