steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'dockerfiles/frontend.dockerfile', '-t', 'gcr.io/dtumlops-410818/frontend:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-410818/frontend']
# options:
#  machineType: 'E2_HIGHCPU_8'
#Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'frontend'
  - '--image'
  - 'gcr.io/dtumlops-410818/frontend:latest'
  - '--region'
  - 'europe-north1'
