name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ matrix.os }}-py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ matrix.os }}-py${{ matrix.python-version }}-pt${{ matrix.pytorch-version }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Get dvc cache directory
      id: dvc-cache-dir
      run: |
          echo "::set-output name=dir::$(dvc cache dir)"
    - uses: actions/cache@v3
      id: dvc-cache # use this to check for `cache-hit` ==> if: steps.dvc-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.dvc-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-dvc-${{ hashFiles('*') }}
        restore-keys: |
          ${{ runner.os }}-dvc-
    - name: Get data
      run: dvc pull -vv
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
